# docker-compose.yml
version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - app-network

  db:
    image: sqlite:latest
    volumes:
      - ./backend/database.db:/var/lib/sqlite3/database.db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
