version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    privileged: true
    ports:
      - "80:80"
    networks:
      rede_front:
        ipv4_address: 10.0.1.3
  
  automacao:
    build:
      context: .
      dockerfile: Dockerfile.automacao
    privileged: true
    volumes:
      - ./ansible:/ansible
    ports:
      - "5001:5001"
    depends_on:
      - db
    networks:
      rede_front:
        ipv4_address: 10.0.1.4
      rede_banco:
        ipv4_address: 10.0.2.5

  backend:
    build: ./backend
    privileged: true
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      rede_banco:
        ipv4_address: 10.0.2.3

  db:
    image: postgres:13
    privileged: true
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
      - "22:22"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      rede_banco:
        ipv4_address: 10.0.2.4

networks:
  rede_front:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24
  
  rede_banco:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.2.0/24

volumes:
  db_data:
